class_name BalanceConfig

const START_MONEY = 3000
const START_WOOD = 150
const START_GOLD = 0
const BASE_BUDGET_FRA = 10

const LOGGING_CAMP_COST_MONEY = 150
const LOGGING_CAMP_COST_WOOD = 0
const LOGGING_CAMP_COST_GOLD = 0
const LOGGING_CAMP_DAYS = 30
const LOGGING_CAMP_PROD_WOOD = 10
const LOGGING_CAMP_PROD_GOLD = 0

const GOLD_MINE_COST_MONEY = 600
const GOLD_MINE_COST_WOOD = 80
const GOLD_MINE_COST_GOLD = 0
const GOLD_MINE_DAYS = 90
const GOLD_MINE_PROD_WOOD = 0
const GOLD_MINE_PROD_GOLD = 1
